/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computermanager;

import javax.swing.DefaultListModel;
import config.*;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author paladini
 */
public class ComputerManager extends javax.swing.JFrame {

    private DefaultListModel list_model = new DefaultListModel();
    private Config config;

    /**
     * Creates new form ComputerManager
     */
    public ComputerManager() {
        initComponents();
        config = Config.getInstance();
        
        computerList_list.setFixedCellHeight(30);
        computerList_list.setFont(computerList_list.getFont().deriveFont(16.0f));
        updateList();
        computerList_list.setModel(list_model);

    }

    private void updateList() {
        if (list_model.size() > 0) {
            list_model.removeAllElements();
        }
        
        for (Computer c : config.getComputers()) {
            list_model.addElement(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeComputer_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerList_list = new javax.swing.JList();
        addComputer_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("[LabSpy] Computer Manager");
        setResizable(false);

        removeComputer_button.setText("Remove Computer");
        removeComputer_button.setEnabled(false);
        removeComputer_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeComputer_buttonMouseClicked(evt);
            }
        });

        computerList_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        computerList_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                computerList_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(computerList_list);

        addComputer_button.setText("Add Computer");
        addComputer_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addComputer_buttonMouseClicked(evt);
            }
        });
        addComputer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addComputer_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeComputer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addComputer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addComputer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeComputer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addComputer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addComputer_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addComputer_buttonActionPerformed

    private void computerList_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_computerList_listValueChanged
        if (!removeComputer_button.isEnabled()) {
            removeComputer_button.setEnabled(true);
        }
    }//GEN-LAST:event_computerList_listValueChanged

    private void removeComputer_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeComputer_buttonMouseClicked
        List<Computer> selectedValues = computerList_list.getSelectedValuesList();

        for (Computer c : selectedValues) {
            config.removeComputer(c);
        }
        
        updateList();
    }//GEN-LAST:event_removeComputer_buttonMouseClicked

    private void addComputer_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addComputer_buttonMouseClicked
        String s = (String) JOptionPane.showInputDialog(null, "Insert the IP of the new machine.");
        
        Computer c = new Computer(s);
        config.addComputer(c);
        updateList();
    }//GEN-LAST:event_addComputer_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputerManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComputerManager cm = new ComputerManager();
                cm.setVisible(true);
                cm.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addComputer_button;
    private javax.swing.JList computerList_list;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeComputer_button;
    // End of variables declaration//GEN-END:variables
}
