package views;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import config.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paladini
 */
public class InstallViewer extends javax.swing.JFrame {

    private List<Computer> listComputer;
    private String globalUsername;
    private String globalPassword;

    /**
     *
     * @param computers
     */
    public InstallViewer(List<Computer> computers) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        listComputer = new ArrayList<Computer>(computers);
        globalUsername = null;
        globalPassword = null;
        next.setEnabled(false);
        setVisible(true);
    }
    
    /**
     *
     */
    public InstallViewer(List<Computer> computers, String username, String password) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        // Cloning the old list.
        listComputer = new ArrayList<Computer>(computers);
        globalUsername = username;
        globalPassword = password;
        next.setEnabled(false);
        setVisible(true);
    }
    
    public void start() {
        progress_bar.setValue(0);
        progress_bar.setMinimum(0);
        progress_bar.setMaximum(listComputer.size());

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                for (int i = 0; i < listComputer.size(); i++) {
                    Computer c = listComputer.get(i);
                    Setup setup = null;

                    if (globalUsername != null && globalPassword != null) {
                        setup = new SetupLinux(c, globalUsername, globalPassword);
                    } else {
                        String username = JOptionPane.showInputDialog(null, "Username (root) for " + c.toString() + ":", "SSH Authentication", JOptionPane.QUESTION_MESSAGE);
                        String password = JOptionPane.showInputDialog(null, "Password of " + username + " user for " + c.toString() + ":", "SSH Authentication", JOptionPane.QUESTION_MESSAGE);
                        setup = new SetupLinux(c, username, password);
                    }

                    // Before start installing this Setup object.
                    if (i == 0) {
                        appendNewText("Installing and configuring " + c.toString() + "...");
                    } else {
                        appendNewText("\nInstalling and configuring " + c.toString() + "...");
                    }
                    status_editable_label.setText("Installing and configuring " + c.toString() + "...");

                    // Doing the work
//                    try {
                        setup.install();
//                        Thread.sleep(1500);
//                    } catch (InterruptedException ex) {
//                        Logger.getLogger(InstallViewer.class.getName()).log(Level.SEVERE, null, ex);
//                    }

                    // After installing Setup object.
                    progress_bar.setValue(i + 1);
                    appendNewText("\nFinished: " + c.toString() + "!\n------------------------------------");

                }
                next.setEnabled(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        status_textarea = new javax.swing.JTextArea();
        progress_bar = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        status_editable_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LabSpy - Setup Process (2/2)");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Installation Status");

        next.setText("Finish!");
        next.setEnabled(false);
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("<html>Please, wait until we configure the computers over SSH. You may be asked to give a SSH username and password for a specific computer - in this case, provide the username and password for root user of the computer.");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        status_textarea.setEditable(false);
        status_textarea.setColumns(20);
        status_textarea.setRows(5);
        jScrollPane1.setViewportView(status_textarea);

        progress_bar.setForeground(new java.awt.Color(102, 153, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Status:");

        status_editable_label.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        status_editable_label.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(status_editable_label))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(progress_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(status_editable_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progress_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        dispose();
    }//GEN-LAST:event_nextMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next;
    private javax.swing.JProgressBar progress_bar;
    private javax.swing.JLabel status_editable_label;
    private javax.swing.JTextArea status_textarea;
    // End of variables declaration//GEN-END:variables

    private void appendNewText(final String txt) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                status_textarea.setText(status_textarea.getText() + txt);
            }
        });
    }

}
